### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#1]
Add a README.md file to describe this repo and how to develop.

**Comment by lopno** [comment]
It would really be helpful if you added the source code in addition to the minified code.

**Comment by sleddog** [comment]
The majority of the source code is in the HTML file.  I'm happy to explain more.

**Comment by allisonsampaio** [comment]
Let me help

**Comment by lopno** [comment]
@sleddog Ah, so it is. My bad.

**Comment by sleddog** [comment]
README is added
