### ISSUE TITLE
Add a POWER bar for shot strength

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#11]
Currently there is no clear power bar for how hard the cue ball is hit.  This ticket could add this ability.

**Comment by alexandrebarbaruiva** [comment]
There's a bug when strength is set too high. My white ball ended up being outside the table pool. Outside even from browser frame.

**Comment by sleddog** [comment]
Well yes... there are bugs for sure :).  This ticket could restrict the velocity value to a max/min value.

**Comment by asi7296** [comment]
I've put up a PR before this referencing issue #16. This commit addresses issue #11. I'm not sure of how to create separate PRs for different issues, I apologise for any inconvenience. I could put the code into a different branch if that helps?

**Comment by sleddog** [comment]
this is looking good.  I think there could be improvements, but I'll make those separate tickets.  Thanks @ryanimpey @asi7296 @alexandrebarbaruiva for the help!
