### ISSUE TITLE
Add a favicon logo for the browser tab

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#14]
There is no favico logo for this pool game.  This ticket will add one (that is pool related).

**Comment by brandsjek** [comment]
I'd like to take this one.

**Comment by brandsjek** [comment]
#20

**Comment by maitreyav** [comment]
Working on it. 😃

**Comment by sleddog** [comment]
Flippy got the 1st one in... Maitreyav if you have a better one its worth seeing.
