### ISSUE TITLE
Add ability to change color of the felt

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#16]
Currently the felt color is statically defined (green).  This ticket could add the ability for a user to change the felt color (maybe using a defined list, or ideally some color picker).

**Comment by digilou** [comment]
Do you still need some help with this @sleddog? I wouldn't mind taking a look.

**Comment by sleddog** [comment]
@digilou sure - I just merged two of these implementations but they are not connected.  Note the felt selector uses a cool color picker, but only changes the bumper color.  The other color drop down changes the background.  You could fix this to be one nice method...

**Comment by sagarchoudhary96** [comment]
@sleddog  is this what you want to happen:
![oct-04-2017 18-19-37](https://user-images.githubusercontent.com/16102594/31176495-a49bfcdc-a930-11e7-953e-36f098d6c2e5.gif)
