### ISSUE TITLE
Improve ball collisions

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#2]
There are a few ways to cause odd collisions.  This ticket will track improving the main collision detecting and resolution functions.

**Comment by kuper-adrian** [comment]
I worked on this problem today and came up with a solution that prevents weird collision angles and "intertwined" balls (which could happen when multiple balls were colliding close to each other, e.g at the beginning). Will open a pull request tomorrow.

**Comment by sleddog** [comment]
@RiotOfViolence oh i'm excited to see this fix!
