### ISSUE TITLE
Split out source code from main index.html into various javascript files

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#4]
To improve development, this ticket could split out the main index.html file's various javascript functions into separate javascript files.

**Comment by okatticus** [comment]
I'd like to take this up.

**Comment by sleddog** [comment]
Go for it @okatticus !

**Comment by okatticus** [comment]
#39 I've split out the html file .(https://github.com/sleddog/pool/pull/39)

**Comment by sleddog** [comment]
Closing this, for now as its easier (my opinion) to do development in one large file for now.
