### ISSUE TITLE
Add cue stick animation based on velocity

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#49]
Currently the cue stick is visible during aiming.  When the shot is fired the cue ball immediately has velocity and the cue stick disappears.  This ticket to add a nice animation after the shot is hit that shows the cue stick go back (based on the amount of velocity selected) then forward, imparting velocity onto the cue ball.

**Comment by BelchingJalapeno** [comment]
I would like to work on this. Do you think the cue stick should wait to be pulled back until after you shoot, or should it start pulling back when you move the power bar?

**Comment by sleddog** [comment]
@BelchingJalapeno sweet!  I think it makes sense to do the 2nd option, to have the cue stick move as you move the power bar (but that may be harder).  Up to you on how to solve it though, have fun and thanks!!
