### ISSUE TITLE
Add a cue stick

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#5]
Currently there is no cue stick.  This ticket could introduce a cue stick to the UI.

**Comment by galczo5** [comment]
I can try to do it tomorrow.

**Comment by galczo5** [comment]
https://github.com/sleddog/pool/pull/41

**Comment by galczo5** [comment]
![2017-10-03-215422_1840x1000_scrot](https://user-images.githubusercontent.com/6080725/31145974-811a21a4-a885-11e7-8dbb-fd68f99021e8.png)

**Comment by sleddog** [comment]
@galczo5 I merged and tested this, and it works great on the 1st shot.  Subsequent shots do not show the cue stick though

**Comment by galczo5** [comment]
Wait for a moment. Stick shows when velocity of ball is less than 0.01
I can change it if you want, I wanted to avoid situation when ball is still moving and stick is visible.

**Comment by sleddog** [comment]
I see... Perhaps this is a tweak to the friction so it slows down faster,
or we can tweak that value.

Another thing, on initial load, the cue stick points away from the rack.
You could make it point directly at the rack if you would like.

**Comment by galczo5** [comment]
https://github.com/sleddog/pool/pull/45

Should be better.
