### ISSUE TITLE
Add properties panel and initial settings

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#52]
There are a number of constants and settings that would be nice to expose in some type of properties panel.

Felt color
bumper color
Max velocity
Friction / max constants
etc...

Add a simple dialog that allows the user to set these, and setup for future settings to be added.

**Comment by medusalix** [comment]
What about using something like [dat.GUI](http://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage)? We could toggle the panel with a function from the developer console.

**Comment by sleddog** [comment]
Yes bingo

**Comment by medusalix** [comment]
Working on it!
