### ISSUE TITLE
Add ability to aim the cue by dragging the mouse

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#62]
Currently you have to click a specific spot for the cue ball to be in order to aim.  This ticket could add the ability to drag and move this "ghost" ball around using the mouse.

**Comment by sleddog** [comment]
@ENiGMA9 wanna try your hand at this one?

**Comment by ENiGMA9** [comment]
@sleddog sure, I'll take it!

**Comment by ENiGMA9** [comment]
@sleddog so, for clarifications, you should be able to aim just by moving the mouse or you have to hold down left click?

**Comment by sleddog** [comment]
@ENiGMA9 I'm thinking when the user drags (holds down via left click) the "ghost" ball (which is the light grey ball they use to aim), it allows this.

Currently you have to click for it to redraw (hard to aim).

Feel free to improve how this works on this ticket.  Thanks in advance!

**Comment by ENiGMA9** [comment]
Hmm, I did a pull request but this one lets you hold left click anywhere in the canvas, if you think it would be better when you drag the grey ball it's okay, I can do that too.

**Comment by sleddog** [comment]
@ENiGMA9 merged this and love it.  Any improvements can be on a followup ticket.  nice job.
