### ISSUE TITLE
Bring back the space key to fire the cue ball

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#65]
We now have a cool power slider on the left side, but you have to use the mouse to fire the shot.  This ticket could bring back the keyboard to "power up" the shot.

The longer you hold the keyboard, the stronger the shot will be (until it maxes out).
A quick press, will be a slow shot
A long hold and release, will be a power shot

**Comment by ENiGMA9** [comment]
I can take care of this

**Comment by ENiGMA9** [comment]
Just sent it #67

**Comment by sleddog** [comment]
@ENiGMA9 well done.  works like a charm.  Wanna take a crack at another one?

**Comment by ENiGMA9** [comment]
@sleddog Sure, I'll take a look, it's also a good opportunity to remove a useless line I forgot in that function.
