### ISSUE TITLE
Add a HOWTO play the game page

### ISSUE THREAD

**Issue by sleddog** [sleddog/pool#9]
There are no instructions on how to play (use the keyboard to fire the ball, select your x/y location of the cue, and the power...)

**Comment by alexandrebarbaruiva** [comment]
Added on #13.

**Comment by sleddog** [comment]
This ticket can be repurposed to add in game instructions (as opposed to on the README).

**Comment by alexandrebarbaruiva** [comment]
Good idea, will do as soon as I can!

**Comment by shailbala** [comment]
Updated README.md on #43.

**Comment by sleddog** [comment]
I'm closing this for now as I rethink how I'd like to handle instructions.  Thanks for the help on this everyone.
